version: "3.9"
services:

  model:
    build:
      context: .
      dockerfile: serving.Dockerfile
    ports:
      - "8501:8501"
    environment:
      MODEL_NAME: deepmac

  client:
    depends_on:
      - model
    build:
      context: .
      dockerfile: client.Dockerfile
    volumes:
      - ./input:/home/tensorflow/input:ro
      - ./output:/home/tensorflow/output
    command: tail -F anything
