version: "3.9"
services:
  app: # todo rename to app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input:/home/tensorflow/input:ro
      - ./output:/home/tensorflow/output
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
