version: "3.9"
services:
  model:
    build:
      context: .
      dockerfile: serving.Dockerfile
    ports:
      - "8501:8501"
    environment:
      MODEL_NAME: deepmac
    network_mode: host  # TODO: Remove, as soon as containers are linked.