version: "3.9"
services:

  model:
    build:
      context: .
      dockerfile: serving.Dockerfile
    ports:
      - "${PORT_BACKEND}"
    environment:
      MODEL_NAME: deepmac

  client:
    depends_on:
      - model
    build:
      context: .
      dockerfile: client.Dockerfile
    volumes:
      - ./data:/home/tensorflow/data
    environment:
      - MODEL_API_URL=http://model:${PORT_BACKEND}/v1/models/deepmac:predict
      - PORT_FRONTEND=${PORT_FRONTEND}
    ports:
      - "${PORT_FRONTEND}:${PORT_FRONTEND}"