version: "3.9"
services:

  model:
    build:
      context: .
      dockerfile: serving.Dockerfile
    ports:
      - ${PORT_BACKEND:-8501}:${PORT_BACKEND:-8501}
    environment:
      MODEL_NAME: deepmac

  client:
    depends_on:
      - model
    build:
      context: .
      dockerfile: client.Dockerfile
    volumes:
      - .:/home/tensorflow/app
    command: python index.py
    environment:
      - MODEL_API_URL=http://model:${PORT_BACKEND:-8501}/v1/models/deepmac:predict
      - PORT_FRONTEND=${PORT_FRONTEND:-8502}
      - PORT_DEBUGGER=${PORT_DEBUGGER:-10001}
      - DEBUGGER=${DEBUGGER:-0}
    ports:
      - ${PORT_FRONTEND:-8502}:${PORT_FRONTEND:-8502}
      - ${PORT_DEBUGGER:-10001}:${PORT_DEBUGGER:-10001}
